spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/owlmailtest"
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate.ddl-auto: none
    defer-datasource-initialization: false
    show-sql: true
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

#  datasource:
#    url: "jdbc:h2:mem:owlmailtest"
#    driverClassName: "org.h2.Driver"
#    username: dd
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console.enabled: true
#  sql:
#    init:
#      mode: always